=== pypi-data/pypi-mirror-28/packages/kadmos/kadmos-0.7.7.tar.gz/kadmos-0.7.7/examples/knowledgebases/ssbj/data-schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- definition of simple elements -->
    <xs:element name="tc" type="xs:decimal"/>
    <xs:element name="h" type="xs:decimal"/>
    <xs:element name="M" type="xs:decimal"/>
    <xs:element name="AR" type="xs:decimal"/>
    <xs:element name="Lambda" type="xs:decimal"/>
    <xs:element name="Sref" type="xs:decimal"/>
    <xs:element name="Cf" type="xs:decimal"/>
    <xs:element name="T" type="xs:decimal"/>
    <xs:element name="WT" type="xs:decimal"/>
    <xs:element name="WF" type="xs:decimal"/>
    <xs:element name="WE" type="xs:decimal"/>
    <xs:element name="D" type="xs:decimal"/>
    <xs:element name="L" type="xs:decimal"/>
    <xs:element name="Theta" type="xs:decimal"/>
    <xs:element name="ESF" type="xs:decimal"/>
    <xs:element name="fin" type="xs:decimal"/>
    <xs:element name="SFC" type="xs:decimal"/>
    <xs:element name="lambda" type="xs:decimal"/>
    <xs:element name="section" type="xs:decimal"/>
    <xs:element name="dpdx" type="xs:decimal"/>
    <xs:element name="R" type="xs:decimal"/>
    <xs:element name="DT" type="xs:decimal"/>
    <xs:element name="Temp" type="xs:decimal"/>
    <xs:element name="sigma" type="xs:string"/>

    <!-- definition of complex elements -->
    <xs:element name="geometry">
      <xs:complexType>
        <xs:all>
            <xs:element ref="tc" minOccurs="0"/>
            <xs:element ref="AR" minOccurs="0"/>
            <xs:element ref="Lambda" minOccurs="0"/>
            <xs:element ref="Sref" minOccurs="0"/>
            <xs:element ref="Theta" minOccurs="0"/>
            <xs:element ref="lambda" minOccurs="0"/>
            <xs:element ref="section" minOccurs="0"/>
        </xs:all>
      </xs:complexType>
    </xs:element>

    <xs:element name="weight">
      <xs:complexType>
        <xs:all>
            <xs:element ref="WE" minOccurs="0"/>
            <xs:element ref="WT" minOccurs="0"/>
            <xs:element ref="WF" minOccurs="0"/>
        </xs:all>
      </xs:complexType>
    </xs:element>

    <xs:element name="other">
      <xs:complexType>
        <xs:all>
            <xs:element ref="D" minOccurs="0"/>
            <xs:element ref="L" minOccurs="0"/>
            <xs:element ref="Cf" minOccurs="0"/>
            <xs:element ref="T" minOccurs="0"/>
            <xs:element ref="DT" minOccurs="0"/>
            <xs:element ref="fin" minOccurs="0"/>
            <xs:element ref="SFC" minOccurs="0"/>
            <xs:element ref="dpdx" minOccurs="0"/>
            <xs:element ref="R" minOccurs="0"/>
            <xs:element ref="sigma" minOccurs="0"/>
        </xs:all>
      </xs:complexType>
    </xs:element>

    <xs:element name="aircraft">
      <xs:complexType>
        <xs:all>
            <xs:element ref="geometry" minOccurs="0"/>
            <xs:element ref="weight" minOccurs="0"/>
            <xs:element ref="other" minOccurs="0"/>
        </xs:all>
      </xs:complexType>
    </xs:element>

    <xs:element name="reference">
      <xs:complexType>
        <xs:all>
            <xs:element ref="h" minOccurs="0"/>
            <xs:element ref="M" minOccurs="0"/>
            <xs:element ref="ESF" minOccurs="0"/>
            <xs:element ref="Temp" minOccurs="0"/>
        </xs:all>
      </xs:complexType>
    </xs:element>

    <xs:element name="data_schema">
      <xs:complexType>
        <xs:all>
            <xs:element ref="aircraft" minOccurs="0"/>
            <xs:element ref="reference" minOccurs="0"/>
        </xs:all>
      </xs:complexType>
    </xs:element>

</xs:schema>

=== pypi-data/pypi-mirror-28/packages/kadmos/kadmos-0.7.7.tar.gz/kadmos-0.7.7/examples/knowledgebases/ssbj/propulsion-output.xml
<?xml version="1.0" encoding="UTF-8"?>
<data_schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data-schema.xsd">
    <aircraft>
        <weight>
            <WE>5748.915355</WE>
        </weight>
        <other>
            <SFC>1.12328</SFC>
            <DT>0.278366</DT>
        </other>
    </aircraft>
    <reference>
        <ESF>1.0</ESF>
        <Temp>1.0</Temp>
    </reference>
</data_schema>

=== pypi-data/pypi-mirror-28/packages/kadmos/kadmos-0.7.7.tar.gz/kadmos-0.7.7/examples/knowledgebases/ssbj/structure-output.xml
<?xml version="1.0" encoding="UTF-8"?>
<data_schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data-schema.xsd">
    <aircraft>
        <geometry>
            <Theta>0.950978</Theta>
        </geometry>
        <weight>
            <WT>49909.58578</WT>
            <WF>7306.20261</WF>
        </weight>
        <other>
            <sigma>1.12255, 1.08170213, 1.0612766, 1.04902128, 1.04085106</sigma>
        </other>
    </aircraft>
</data_schema>

=== pypi-data/pypi-mirror-28/packages/kadmos/kadmos-0.7.7.tar.gz/kadmos-0.7.7/examples/knowledgebases/ssbj/propulsion-input.xml
<?xml version="1.0" encoding="UTF-8"?>
<data_schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data-schema.xsd">
    <aircraft>
        <other>
            <T>0.5</T>
            <D>12193.7018</D>
        </other>
    </aircraft>
    <reference>
            <h>45000.</h>
            <M>1.6</M>
    </reference>
</data_schema>

=== pypi-data/pypi-mirror-28/packages/kadmos/kadmos-0.7.7.tar.gz/kadmos-0.7.7/examples/knowledgebases/ssbj/performance-input.xml
<?xml version="1.0" encoding="UTF-8"?>
<data_schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data-schema.xsd">
    <aircraft>
        <weight>
            <WT>49909.58578</WT>
            <WF>7306.20261</WF>
        </weight>
        <other>
            <fin>4.093062</fin>
            <SFC>1.12328</SFC>
        </other>
    </aircraft>
    <reference>
        <h>45000.</h>
        <M>1.6</M>
    </reference>
</data_schema>

=== pypi-data/pypi-mirror-28/packages/kadmos/kadmos-0.7.7.tar.gz/kadmos-0.7.7/examples/knowledgebases/ssbj/aerodynamics-input.xml
<?xml version="1.0" encoding="UTF-8"?>
<data_schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data-schema.xsd">
    <aircraft>
        <geometry>
            <tc>0.05</tc>
            <AR>5.5</AR>
            <Lambda>55.0</Lambda>
            <Sref>1000.0</Sref>
            <Theta>0.950978</Theta>
        </geometry>
        <weight>
            <WT>49909.58578</WT>
        </weight>
        <other>
            <Cf>1.0</Cf>
        </other>
    </aircraft>
    <reference>
        <h>45000.</h>
        <M>1.6</M>
        <ESF>1.0</ESF>
    </reference>
</data_schema>

=== pypi-data/pypi-mirror-28/packages/kadmos/kadmos-0.7.7.tar.gz/kadmos-0.7.7/examples/knowledgebases/ssbj/structure-input.xml
<?xml version="1.0" encoding="UTF-8"?>
<data_schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data-schema.xsd">
    <aircraft>
        <geometry>
            <tc>0.05</tc>
            <AR>5.5</AR>
            <Lambda>55.0</Lambda>
            <Sref>1000.0</Sref>
            <lambda>0.25</lambda>
            <section>1.0</section>
        </geometry>
        <weight>
            <WE>5748.915355</WE>
        </weight>
        <other>
            <L>49909.58578</L>
        </other>
    </aircraft>
</data_schema>
